export const BASE_URL = 'https://drivingschoolindia.com/webmasters_admin/api/';

export const ENDPOINTS = {
  LOGIN: `${BASE_URL}login.php`,
  Trainer_Profile: `${BASE_URL}trainer_profile.php`,
  Trainer_Student_List: `${BASE_URL}trainer_student_list.php`,
  Status_Verification: `${BASE_URL}status_verify.php`,
  Trainer_Time_wise_Show: `${BASE_URL}trainer_time.php`,
  Trainer_Attendence: `${BASE_URL}trainer_attendance.php`,
  Show_Trainer_Attendence_List: `${BASE_URL}trainer_attendance_list.php`,
  Show_Trainer_Date_Wise: `${BASE_URL}trainer_report_list.php`,
  Slot_wise_check_form: `${BASE_URL}slot_wise_check_form.php`,
  Add_Trainer_Student: `${BASE_URL}add_trainer_student.php`,
  Show_Student_Name: `${BASE_URL}show_student_name.php`,
  Add_Trainer_Leave: `${BASE_URL}add_trainer_leave.php`,
  Trainer_Leave_List: `${BASE_URL}trainer_leave_list.php`,
  Delete_Trainer_Leave: `${BASE_URL}delete_trainer_leave.php`,
  Update_Trainer_Leave: `${BASE_URL}update_trainer_leave.php`,
  Trainer_Change_Password: `${BASE_URL}change_trainer_pswd.php`,
  Add_Advance_Payment: `${BASE_URL}add_advance_payment.php`,
  List_Advance_Payment: `${BASE_URL}list_advance_payment.php`,
  Update_Advance_Payment: `${BASE_URL}update_advance_payment.php`,
  Delete_Advance_Payment: `${BASE_URL}delete_advance_payment.php`,
  Trainer_Reward_Point: `${BASE_URL}trainer_reward_point.php`,
  Manager_Staff_Leave_List: `${BASE_URL}manager_staff_leave_list.php`,
  Manager_Staff_Advance_Payment: `${BASE_URL}manager_staff_advance_payment.php`,
  Manager_Staff_Attendence_List: `${BASE_URL}manager_group_staff_attendance_list.php`,
  Leave_Status: `${BASE_URL}leave_status.php`,
  Advance_Payment_Status: `${BASE_URL}advance_payment_status.php`,
  Show_Attendence_Detail: `${BASE_URL}show_attendance_detail.php`,
};
